// copy.js: 시뮬레이터 패널 문구. 영문을 먼저 쓰고 한국어는 따로 쓴다(docs/VOICE.md). 화면에서는 <Bi>로 그린다.
// 기기 화면 안의 문구는 flow/copy.js(K2)가 맡고 여기에는 두지 않는다.
export const PANEL = {
  en: {
    eyebrow: 'GY-01 UrbanEdge',
    title: 'Kiosk simulator',
    titleShort: 'Simulator',
    intro: "The machine's own screen, inside the machine. Tap it, or jump to any step below.",
    deviceLabel: 'Device',
    fullscreen: 'Open full screen in new window',
    fullscreenNote: 'Opens only the program screen, with a short tour.',
    blocked: 'Your browser blocked the new window. Allow pop-ups here, or',
    blockedLink: 'open it in a tab',
    tour: 'Take the tour',
    restart: 'Restart',
    stepsHead: 'Journey steps',
    stepsHint: 'Pick a step to switch the screen to it',
    settingsHead: 'Settings',
    camera: 'Camera',
    cameraSample: 'Sample photos',
    cameraLive: 'My webcam',
    cameraNote: 'The webcam feed stays in this tab and is never uploaded.',
    annotate: 'Label the parts',
    stateHead: 'Machine state',
    hint: 'Highlighted part',
    none: 'None',
    led: 'Light bars',
    ledOn: 'Lit',
    ledOff: 'Off',
    lens: 'Lens light',
    lensOn: 'On',
    lensOff: 'Off',
    print: 'Print',
    printOut: 'Coming out',
    partsHead: 'Parts',
    noteHead: 'Good to know',
    note: 'Payment is part of the flow, but nothing is charged in this simulator.',
    keys: 'With focus in this panel, arrow keys move between steps and Esc goes back to the start.',
    stepOf: (i, n) => `Step ${i} of ${n}`,
    live: (z) => `Highlighted on the machine: ${z}`,
  },
  ko: {
    eyebrow: 'GY-01 어반엣지',
    title: '키오스크 시뮬레이터',
    titleShort: '시뮬레이터',
    intro: '기기 화면을 기기 모양 그대로 담았습니다. 화면을 직접 누르거나 아래에서 원하는 단계로 건너뛰세요.',
    deviceLabel: '기기',
    fullscreen: '새 창에서 전체 화면으로 열기',
    fullscreenNote: '프로그램 화면만 열리며 짧은 사용법 안내가 함께 나옵니다.',
    blocked: '브라우저가 새 창을 막았습니다. 이 사이트의 팝업을 허용하거나',
    blockedLink: '새 탭으로 열기',
    tour: '사용법 안내 보기',
    restart: '처음으로',
    stepsHead: '이용 단계',
    stepsHint: '단계를 누르면 화면이 그 단계로 바뀝니다',
    settingsHead: '설정',
    camera: '카메라',
    cameraSample: '샘플 사진',
    cameraLive: '내 웹캠',
    cameraNote: '웹캠 영상은 이 탭 안에서만 쓰이며 업로드되지 않습니다.',
    annotate: '부품 이름 표시',
    stateHead: '기기 상태',
    hint: '강조 부위',
    none: '없음',
    led: '조명바',
    ledOn: '점등',
    ledOff: '소등',
    lens: '렌즈 표시등',
    lensOn: '켜짐',
    lensOff: '꺼짐',
    print: '인화물',
    printOut: '배출 중',
    partsHead: '부품',
    noteHead: '알아 두기',
    note: '결제도 이용 흐름에 포함되지만 이 시뮬레이터에서는 실제로 청구되지 않습니다.',
    keys: '이 패널에 포커스가 있으면 화살표 키로 단계 사이를 이동하고 Esc로 처음으로 돌아갑니다.',
    stepOf: (i, n) => `${n}단계 중 ${i}단계`,
    live: (z) => `기기에서 강조 중인 부위: ${z}`,
  },
}
