// copy.js: 시뮬레이터 패널 문구. 기기 화면 안의 문구는 flow/copy.js(K2)가 맡고 여기에는 두지 않는다.
export const PANEL = {
  ko: {
    title: '키오스크 시뮬레이터',
    deviceLabel: '기기',
    stepsHead: '단계 이동',
    stepsHint: '단계를 누르면 기기 화면이 그 단계로 바뀐다',
    settingsHead: '설정',
    language: '언어',
    camera: '카메라 모드',
    cameraSample: '샘플',
    cameraLive: '웹캠',
    annotate: '부품 주석 보기',
    restart: '처음으로',
    openScreen: '화면만 전체 화면으로 열기',
    stateHead: '기기 상태',
    hint: '강조 부위',
    none: '없음',
    led: 'LED 조명바',
    ledOn: '점등',
    ledOff: '소등',
    lens: '렌즈 표시등',
    lensOn: '켜짐',
    lensOff: '꺼짐',
    print: '인화물',
    printOut: '배출 중',
    partsHead: '부품 주석',
    paymentHead: '구현 범위',
    payment: '결제는 구현 범위에서 제외. 프레임 선택 다음에 결제가 끝난 것으로 가정한다.',
    keys: '패널에 포커스가 있을 때 화살표 키는 단계 이동, Esc는 처음으로',
    live: (z) => `기기 부위 강조: ${z}`,
  },
  en: {
    title: 'Kiosk simulator',
    deviceLabel: 'Device',
    stepsHead: 'Jump to step',
    stepsHint: 'Pick a step to switch the device screen to it',
    settingsHead: 'Settings',
    language: 'Language',
    camera: 'Camera mode',
    cameraSample: 'Sample',
    cameraLive: 'Webcam',
    annotate: 'Show part annotations',
    restart: 'Restart',
    openScreen: 'Open the screen only, full window',
    stateHead: 'Device state',
    hint: 'Highlighted part',
    none: 'None',
    led: 'LED light bars',
    ledOn: 'Lit',
    ledOff: 'Off',
    lens: 'Lens indicator',
    lensOn: 'On',
    lensOff: 'Off',
    print: 'Print',
    printOut: 'Coming out',
    partsHead: 'Part annotations',
    paymentHead: 'Scope',
    payment: 'Payment is out of scope. The flow assumes payment is done right after frame selection.',
    keys: 'With focus inside this panel, arrow keys change the step and Esc restarts',
    live: (z) => `Device part highlighted: ${z}`,
  },
}
